'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createService}=require('../lib/newsletter-reminders/core.cjs');
const START=Date.parse('2026-10-09T10:00:00Z'),HOUR=3600000;
function fixture() {
 const entries=new Map(),jobs=[],sent=[];let clock=START,exists=false,status='delivered',failure=false,checks=0;
 const env={DOI_REMINDER_ENABLED:'true',DOI_REMINDER_START_AT:new Date(START).toISOString(),DOI_REMINDER_WEBHOOK_SECRET:'w'.repeat(32),DOI_REMINDER_HASH_SECRET:'h'.repeat(32),BREVO_API_KEY:'b'.repeat(32)};
 const store={read:async k=>entries.get(k)||null,create:async(k,v)=>{if(entries.has(k))return false;entries.set(k,v);return true;},remove:async k=>entries.delete(k),scan:async function*(){}};
 const brevo={contactExists:async()=>{checks++;return exists;},deliveryStatus:async()=>status,sendReminder:async(email,payload)=>{sent.push({email,...payload});if(failure)throw Error('timeout');}};
 const svc=createService({env,store,queue:{send:async(...args)=>jobs.push(args)},brevo,now:()=>clock});
 const event={event:'request',template_id:9,email:'example@example.invalid','message-id':'<doi-original>',ts_event:START/1000};
 return {svc,env,store,entries,jobs,sent,event,brevo,auth:'Bearer '+env.DOI_REMINDER_WEBHOOK_SECRET,setTime:v=>clock=v,setExists:v=>exists=v,setStatus:v=>status=v,setFailure:v=>failure=v,get checks(){return checks;}};
}
test('one reminder after 48h; no early send; replay never duplicates',async()=>{const f=fixture();assert.equal((await f.svc.register(f.event,f.auth)).status,204);assert.equal(f.jobs[0][2].delaySeconds,172800);assert.equal(f.jobs[0][2].retentionSeconds,604800);assert.equal(JSON.stringify(f.jobs).includes(f.event.email),false);await assert.rejects(f.svc.dispatch(f.jobs[0][1]),/not_due/);f.setTime(START+48*HOUR);assert.equal(await f.svc.dispatch(f.jobs[0][1]),'sent');assert.equal(f.sent.length,1);assert.equal(f.checks,2);assert.equal(await f.svc.dispatch(f.jobs[0][1]),'already_handled');assert.equal(f.sent.length,1);assert.equal([...f.entries.values()].some(v=>v.email),false);});
test('confirmed/unsubscribed/existing contact is suppressed',async()=>{const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+48*HOUR);f.setExists(true);assert.equal(await f.svc.dispatch(f.jobs[0][1]),'suppressed');assert.equal(f.sent.length,0);});
test('confirmation during processing is caught by final contact check',async()=>{const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+48*HOUR);let calls=0;f.brevo.contactExists=async()=>++calls===2;assert.equal(await f.svc.dispatch(f.jobs[0][1]),'suppressed');assert.equal(f.sent.length,0);});
test('duplicate submissions and concurrent queue delivery cannot double send',async()=>{const f=fixture();await Promise.all([f.svc.register(f.event,f.auth),f.svc.register({...f.event,'message-id':'<second>'},f.auth)]);f.setTime(START+48*HOUR);await Promise.all(f.jobs.map(j=>f.svc.dispatch(j[1])));assert.equal(f.sent.length,1);});
test('uncertain send is never retried',async()=>{const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+48*HOUR);f.setFailure(true);await assert.rejects(f.svc.dispatch(f.jobs[0][1]));assert.equal(await f.svc.dispatch(f.jobs[0][1]),'already_handled');assert.equal(f.sent.length,1);});
test('provider read failure does not mark a reminder attempted',async()=>{const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+48*HOUR);f.brevo.contactExists=async()=>{throw Error('unavailable');};await assert.rejects(f.svc.dispatch(f.jobs[0][1]));assert.equal(f.sent.length,0);assert.equal([...f.entries.keys()].some(k=>k.includes('/receipts/')),false);});
test('missing delivery, bounce or complaint never sends',async()=>{for(const status of ['unknown','blocked']){const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+48*HOUR);f.setStatus(status);assert.equal(await f.svc.dispatch(f.jobs[0][1]),'suppressed');assert.equal(f.sent.length,0);}});
test('unauthorized, other templates and old events do not enter queue',async()=>{const f=fixture();assert.equal((await f.svc.register(f.event,'wrong')).status,401);await f.svc.register({...f.event,template_id:5},f.auth);await f.svc.register({...f.event,ts_event:(START-1)/1000},f.auth);assert.equal(f.jobs.length,0);});
test('activation can be disabled without any sends',async()=>{const f=fixture();f.env.DOI_REMINDER_ENABLED='false';await assert.rejects(f.svc.register(f.event,f.auth),/disabled/);assert.equal(f.sent.length,0);});
test('queue publication failure can recover from persisted registration',async()=>{const f=fixture();const service=createService({env:f.env,store:f.store,queue:{send:async()=>{throw Error('offline');}},brevo:f.brevo,now:()=>START});await assert.rejects(service.register(f.event,f.auth));assert.equal((await f.svc.register(f.event,f.auth)).status,204);assert.equal(f.jobs.length,1);});
test('expired pending requests are discarded',async()=>{const f=fixture();await f.svc.register(f.event,f.auth);f.setTime(START+8*24*HOUR);assert.equal(await f.svc.dispatch(f.jobs[0][1]),'expired');assert.equal(f.sent.length,0);});
