'use strict';
const fs=require('node:fs'),path=require('node:path');
const {loadContent,fingerprint,root}=require('../../core.cjs');
const ids=['knieprothese-bariatrische-chirurgie-obesitas-knieartrose','leonie-meihuizen-onderzoeker-transmuraal-tilburg-cohort','obesitasmedicatie-knieartrose-minder-pijn-minder-bewegen'];
const articles=ids.map(id=>loadContent().articles.find(a=>a.id===id));
if(articles.some(a=>!a))throw Error('Artikel ontbreekt');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro='In deze eerste nieuwsbrief staan artrose, obesitas en het Transmuraal Tilburg Cohort centraal. Je leest over bariatrische chirurgie en een knieprothese, de start van Leonie Meihuizen als onderzoeker en obesitasmedicatie in relatie tot pijn en bewegen. Deze onderwerpen laten ieder op hun eigen manier zien hoe behandeling, leefstijl en onderzoek steeds meer met elkaar samenhangen.';
const summaries={
  'knieprothese-bariatrische-chirurgie-obesitas-knieartrose':'Bij mensen met ernstige obesitas en gevorderde knieartrose kunnen zowel een knieprothese als bariatrische chirurgie aan de orde zijn. In de SWIFT-studie verbeterde het functioneren in beide groepen; na bariatrische chirurgie stelde een deel van de deelnemers de knieprothese uit. De studie bewijst echter niet dat één volgorde voor iedereen beter is. Ook een recente meta-analyse liet geen duidelijk verschil zien in nieuwe operaties aan de knieprothese. De keuze blijft daarom een individuele afweging.',
  'leonie-meihuizen-onderzoeker-transmuraal-tilburg-cohort':'Sinds 1 september werkt fysiotherapeut Leonie Meihuizen één dag per week als onderzoeker binnen het Transmuraal Tilburg Cohort. Zij helpt bij de verdere opbouw van het digitale zorgpad en de voorbereiding van prospectieve gegevensverzameling. Het cohort moet stap voor stap inzicht geven in pijn, functioneren, bewegen, kwaliteit van leven en zorggebruik bij mensen met artrose en obesitas.',
  'obesitasmedicatie-knieartrose-minder-pijn-minder-bewegen':'Een studie uit 2024 liet bij mensen met obesitas en knieartrose tijdens behandeling met semaglutide meer gewichtsverlies en minder kniepijn zien. Een andere, op ENDO 2026 gepresenteerde cohortstudie zag na de start van GLP-1-medicatie juist minder dagelijkse beweging. De studies beantwoorden verschillende vragen, maar maken samen duidelijk dat gewicht, pijn, spierkracht en functioneren niet automatisch dezelfde kant op bewegen.'
};
const closingCta=`<div style="border-top:1px solid #d8d5ca;padding:28px 0 8px"><h2 style="font-size:23px;line-height:1.25;margin:0 0 12px">Meer lezen of iemand tippen?</h2><p style="margin:0 0 16px">Op MatthijsVanDam.nl vind je de volledige artikelen en meer nieuws over artrose, obesitas en het Transmuraal Tilburg Cohort.</p><p style="margin:0 0 18px">Ken je iemand voor wie deze onderwerpen relevant zijn? Stuur mijn nieuwsbrief dan gerust door. Daarmee help je om de informatie en mijn onderzoek verder onder de aandacht te brengen.</p><a href="https://www.matthijsvandam.nl/artikelen.html" style="color:#244c3d;font-weight:bold">Bekijk meer op de website →</a></div>`;
const base=JSON.parse(fs.readFileSync(path.join(__dirname,'../../native/test-campaign.json')));
const start=base.htmlContent.indexOf('<div style="border-top:');
const end=base.htmlContent.indexOf('<p>Hartelijke groet,',start);
const blocks=articles.map((a,index)=>`<div style="border-top:1px solid #d8d5ca;padding:${index===0?'30px':'26px'} 0"><img src="https://www.matthijsvandam.nl/${esc(a.image)}" alt="${esc(a.imageAlt)}" width="552" style="display:block;width:100%;max-width:552px;height:auto;border:0;border-radius:6px;margin:0 0 18px"><p style="color:#244c3d;font-size:11px;letter-spacing:2px;margin:0 0 10px">${index===0?'UITGELICHT · ':''}${esc(a.label)}</p><h2 style="font-size:${index===0?'25px':'23px'};line-height:1.25;margin:0 0 12px">${esc(a.title)}</h2><p style="margin:0 0 16px">${esc(summaries[a.id])}</p><a href="https://www.matthijsvandam.nl/${esc(a.url)}" style="color:#244c3d;font-weight:bold">Lees het hele artikel →</a></div>`).join('');
let html=base.htmlContent.slice(0,start)+blocks+closingCta+base.htmlContent.slice(end);
const wordmark='<a href="https://matthijsvandam.nl/" style="color:#17201c;text-decoration:none;font-size:24px;font-weight:700;letter-spacing:-.7px">MatthijsvanDam<span style="color:#244c3d">.nl</span></a>';
const branded='<table role="presentation" cellspacing="0" cellpadding="0" style="border-collapse:collapse"><tr><td style="padding:0 12px 0 0;vertical-align:middle"><img src="https://www.matthijsvandam.nl/assets/logo-mvd-tree-mark.png" alt="" width="62" height="62" style="display:block;width:62px;height:62px;border:0"></td><td style="vertical-align:middle">'+wordmark+'</td></tr></table>';
html=html.replace(wordmark,branded).replace('Nieuwsbrief 2026 · nr. 1 · vormgevingsvoorbeeld','Artrose, obesitas en het Transmuraal Tilburg Cohort').replace('In deze editie','Artrose, obesitas en onderzoek').replace('Dit is een technische proef van de nieuwsbrief. Hiermee controleren we de vormgeving en de links om je voorkeuren te wijzigen of je uit te schrijven.',intro).replace(intro+'</p>',intro+'</p><p style="margin:18px 0 22px">Hartelijke groet,<br><strong>Matthijs</strong></p>').replace('<p style="background:#dce8df;padding:14px;border-radius:6px;font-size:14px">Dit is een technische proef. De artikelteksten hieronder zijn plaatsaanduidingen en geen nieuwsartikelen.</p>','').replace('<p>Hartelijke groet,<br><strong>Matthijs van Dam</strong></p>','').replace('Technische proef · MatthijsvanDam.nl','MatthijsvanDam.nl · Nieuwsbrief');
const payload={...base,name:'MVD 2026-01 — Artrose, obesitas en cohort — CONCEPT NIET VERZENDEN',subject:'Artrose, obesitas en het Transmuraal Tilburg Cohort',htmlContent:html};
fs.writeFileSync(path.join(__dirname,'campaign-draft.json'),JSON.stringify(payload,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'preview.html'),html.replace('<body ','<body data-editorial-status="concept" ').replace('<td style="padding:8px 8px 24px">','<td style="padding:8px 8px 24px"><p style="color:#5d675f;font-size:13px">Concept · nog niet goedgekeurd voor verzending</p>'));
fs.writeFileSync(path.join(__dirname,'editorial-review.json'),JSON.stringify({status:'concept',distributionApproved:false,recipients:[],scheduledAt:null,articles:articles.map(a=>({id:a.id,title:a.title,summary:summaries[a.id],url:a.url,fingerprint:fingerprint(a,fs.readFileSync(path.join(root,a.url)))}))},null,2)+'\n');
console.log('Concepteditie gebouwd: drie bestaande artikelen, geen distributievrijgave, geen ontvangers, geen verzending.');
