'use strict';
const fs=require('node:fs'),path=require('node:path');
const {loadContent,fingerprint,root}=require('../../core.cjs');
const ids=['knieprothese-bariatrische-chirurgie-obesitas-knieartrose','leonie-meihuizen-onderzoeker-transmuraal-tilburg-cohort','obesitasmedicatie-knieartrose-minder-pijn-minder-bewegen'];
const articles=ids.map(id=>loadContent().articles.find(a=>a.id===id));
if(articles.some(a=>!a))throw Error('Artikel ontbreekt');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro='In deze eerste nieuwsbrief staan artrose, obesitas en het Transmuraal Tilburg Cohort centraal. Je leest over bariatrische chirurgie en een knieprothese, de start van Leonie Meihuizen als onderzoeker en obesitasmedicatie in relatie tot pijn en bewegen.';
const base=JSON.parse(fs.readFileSync(path.join(__dirname,'../../native/test-campaign.json')));
const start=base.htmlContent.indexOf('<div style="border-top:');
const end=base.htmlContent.indexOf('<p>Hartelijke groet,',start);
const blocks=articles.map(a=>`<div style="border-top:1px solid #d8d5ca;padding:26px 0"><img src="https://www.matthijsvandam.nl/${esc(a.image)}" alt="${esc(a.imageAlt)}" width="552" style="display:block;width:100%;max-width:552px;height:auto;border:0;border-radius:6px;margin:0 0 18px"><p style="color:#244c3d;font-size:11px;letter-spacing:2px;margin:0 0 10px">${esc(a.label)}</p><h2 style="font-size:23px;line-height:1.25;margin:0 0 12px">${esc(a.title)}</h2><p style="margin:0 0 16px">${esc(a.summary)}</p><a href="https://www.matthijsvandam.nl/${esc(a.url)}" style="color:#244c3d;font-weight:bold">Lees het artikel →</a></div>`).join('');
let html=base.htmlContent.slice(0,start)+blocks+base.htmlContent.slice(end);
html=html.replace('Nieuwsbrief 2026 · nr. 1 · vormgevingsvoorbeeld','Artrose, obesitas en het Transmuraal Tilburg Cohort').replace('In deze editie','Artrose, obesitas en onderzoek').replace('Dit is een technische proef van de nieuwsbrief. Hiermee controleren we de vormgeving en de links om je voorkeuren te wijzigen of je uit te schrijven.',intro).replace('<p style="background:#dce8df;padding:14px;border-radius:6px;font-size:14px">Dit is een technische proef. De artikelteksten hieronder zijn plaatsaanduidingen en geen nieuwsartikelen.</p>','').replace('Technische proef · MatthijsvanDam.nl','MatthijsvanDam.nl · Nieuwsbrief');
const payload={...base,name:'MVD 2026-01 — Artrose, obesitas en cohort — CONCEPT NIET VERZENDEN',subject:'Artrose, obesitas en het Transmuraal Tilburg Cohort',htmlContent:html};
fs.writeFileSync(path.join(__dirname,'campaign-draft.json'),JSON.stringify(payload,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'preview.html'),html.replace('<body ','<body data-editorial-status="concept" ').replace('<td style="padding:8px 8px 24px">','<td style="padding:8px 8px 24px"><p style="color:#5d675f;font-size:13px">Concept · nog niet goedgekeurd voor verzending</p>'));
fs.writeFileSync(path.join(__dirname,'editorial-review.json'),JSON.stringify({status:'concept',distributionApproved:false,recipients:[],scheduledAt:null,articles:articles.map(a=>({id:a.id,title:a.title,summary:a.summary,url:a.url,fingerprint:fingerprint(a,fs.readFileSync(path.join(root,a.url)))}))},null,2)+'\n');
console.log('Concepteditie gebouwd: drie bestaande artikelen, geen distributievrijgave, geen ontvangers, geen verzending.');
