'use strict';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css='font-family:Inter,Arial,sans-serif;line-height:1.65;color:#17201c';
function shell(title,content,footer='MatthijsvanDam.nl · Nieuwsbrief') {
 return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escape(title)}</title></head><body style="margin:0;background:#f7f4ed;${css}"><table role="presentation" style="width:100%;border-collapse:collapse"><tr><td style="padding:28px 16px"><table role="presentation" style="width:100%;max-width:600px;margin:auto;border-collapse:collapse"><tr><td style="padding:8px 8px 24px"><a href="https://matthijsvandam.nl/" style="color:#17201c;text-decoration:none;font-size:24px;font-weight:700;letter-spacing:-.7px">MatthijsvanDam<span style="color:#244c3d">.nl</span></a></td></tr><tr><td style="background:#fffdf8;border-top:5px solid #244c3d;padding:30px 24px">${content}</td></tr><tr><td style="padding:22px 8px;color:#5d675f;font-size:12px">${escape(footer)}</td></tr></table></td></tr></table></body></html>`;
}
function button(url,label) {
 const parsed=new URL(url);
 if(!['http:','https:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Ongeldige link.');
 return `<a href="${escape(url)}" style="display:inline-block;background:#244c3d;color:#fffdf8;padding:13px 18px;border-radius:6px;text-decoration:none;font-size:16px;font-weight:bold">${escape(label)}</a>`;
}
function renderConfirmationMail({url,streams,minutes,consentText}) {
 const subject='Bevestig je inschrijving voor mijn nieuwsbrief';
 const html=shell(subject,`<p style="margin:0 0 12px;color:#244c3d;font-size:12px;letter-spacing:2px;text-transform:uppercase">Nieuwsbrief</p><h1 style="font-size:28px;line-height:1.2;letter-spacing:-.7px;margin:0 0 24px">Blijf op de hoogte</h1><p>Je hebt je aangemeld voor mijn nieuwsbrief. Je kiest zelf welke onderwerpen je wilt volgen.</p><ul style="padding-left:22px;margin:24px 0">${streams.map(s=>`<li style="margin:8px 0">${escape(s)}</li>`).join('')}</ul><p style="background:#dce8df;padding:16px;border-radius:6px">${escape(consentText)} Je ontvangt maximaal 12 keer per jaar een nieuwsbrief.</p><p style="margin:26px 0">${button(url,'Bekijk en bevestig je inschrijving')}</p><p style="font-size:14px;color:#5d675f">Op de website bevestig je je inschrijving nog één keer. Deze link is ${minutes} minuten geldig. Een nieuwe aanvraag maakt deze link ongeldig.</p><p style="font-size:14px;color:#5d675f">Heb je je niet zelf aangemeld? Gebruik de link dan niet. Je kunt dit bericht negeren.</p><p style="margin-top:28px">Hartelijke groet,<br><strong>Matthijs van Dam</strong></p>`);
 return {subject,html,text:['MatthijsvanDam.nl',subject,...streams,consentText,'Maximaal 12 nieuwsbrieven per jaar.',url,`Bevestig op de website. Link geldig: ${minutes} minuten. Een nieuwe aanvraag vervangt deze link.`,'Niet zelf aangemeld? Negeer dit bericht.'].join('\n')};
}
function renderNewsletterExample({year=2026,number=1,firstName='',title='In deze editie',introduction='',topics=['voetscreening','het wandelproject WE Walk']}={}) {
 // Local example only. Production must supply topics from the recipient's selected articles.
 const cleanTopics=[...new Set(topics.map(topic=>String(topic).trim()).filter(Boolean))];
 const subjectList=new Intl.ListFormat('nl',{style:'long',type:'conjunction'}).format(cleanTopics);
 const intro=String(introduction).trim()||(subjectList?`In deze nieuwsbrief deel ik nieuwe artikelen over ${subjectList}. Ik heb ze voor je bij elkaar gezet. Veel leesplezier!`:'Ik heb de nieuwe artikelen voor je bij elkaar gezet. Veel leesplezier!');
 const greeting=String(firstName).trim()?`Beste ${String(firstName).trim()},`:'Beste lezer,';
 // Example metadata; actual issue numbering belongs to the future sending register.
 if(!Number.isInteger(year)||year<2000||year>9999||!Number.isInteger(number)||number<1||number>12)throw Error('Ongeldig nieuwsbriefjaar of nummer.');
 const articles=[['ONDERWERP','Hier komt de titel van je artikel','Hier komt de korte introductie van een artikel dat je voor de nieuwsbrief hebt vrijgegeven.','article-footprint-quick-scan-editorial.jpg','Voetscreening met werkschoenen, inlegzolen en een anatomisch voetmodel.'],['PROJECT','Een update uit een project','Hier komt een tweede artikel, passend bij de gekozen onderwerpen en doelgroep.','project-we-walk-editorial.jpg','Smartphone met AR-wandelroute op een rustige campus.']];
 return shell(`Nieuwsbrief ${year} · nr. ${number} · vormgevingsvoorbeeld`,`<table role="presentation" style="width:100%;border-collapse:collapse;color:#244c3d;font-size:12px;letter-spacing:2px"><tr><td style="padding:0;text-align:left">NIEUWSBRIEF</td><td align="right" style="padding:0 0 0 8px;text-align:right;white-space:nowrap">${year} · NR. ${number}</td></tr></table><h1 style="font-size:34px;line-height:1.15;letter-spacing:-1px;margin:16px 0;overflow-wrap:anywhere">${escape(title)}</h1><p style="margin:24px 0 12px">${escape(greeting)}</p>${intro.split(/\n\s*\n/).map(paragraph=>`<p style="margin:0 0 16px">${escape(paragraph).replace(/\n/g,"<br>")}</p>`).join('')}<p style="background:#dce8df;padding:14px;border-radius:6px;font-size:14px">Dit is een lokaal voorbeeld van de vormgeving. De naam is fictief, de afbeeldingen komen van de website en de artikelteksten zijn plaatsaanduidingen; er is niets klaargezet voor verzending.</p>${articles.map(([tag,title,summary,image,alt])=>`<div style="border-top:1px solid #d8d5ca;padding:26px 0"><img src="/newsletter-images/${escape(image)}" alt="${escape(alt)}" width="552" style="display:block;width:100%;max-width:552px;height:auto;border:0;border-radius:6px;margin:0 0 18px"><p style="color:#244c3d;font-size:11px;letter-spacing:2px;margin:0 0 10px">${tag}</p><h2 style="font-size:23px;line-height:1.25;margin:0 0 12px">${title}</h2><p style="margin:0 0 16px">${summary}</p><span style="color:#244c3d;font-weight:bold">Lees het artikel →</span></div>`).join('')}<p>Hartelijke groet,<br><strong>Matthijs van Dam</strong></p><p style="font-size:13px;color:#5d675f;border-top:1px solid #d8d5ca;padding-top:20px">Je ontvangt deze nieuwsbrief omdat je je hebt ingeschreven. Maximaal 12 keer per jaar.<br>Voorkeuren wijzigen · Uitschrijven <em>(links volgen bij ingebruikname)</em></p>`,'Lokaal vormgevingsvoorbeeld · niet gepubliceerd of verstuurd');
}
function renderNativeConfirmationMail() {
 const subject='Bevestig je inschrijving voor mijn nieuwsbrief';
 // Brevo's native form placeholder, copied from its default DOI template.
 const link=button('https://example.invalid/native-confirmation','Bevestig mijn inschrijving').replace('https://example.invalid/native-confirmation','{{ doubleoptin }}');
 const html=shell(subject,`<p style="margin:0 0 12px;color:#244c3d;font-size:12px;letter-spacing:2px">NIEUWSBRIEF</p><h1 style="font-size:28px;line-height:1.2;margin:0 0 24px">Bevestig je inschrijving</h1><p>Je hebt je aangemeld voor mijn nieuwsbrief. Klik hieronder om je inschrijving te bevestigen.</p><p>Je ontvangt nieuws over de onderwerpen die je hebt gekozen, maximaal 12 keer per jaar. Je kunt je altijd uitschrijven.</p><p style="margin:26px 0">${link}</p><p style="font-size:14px;color:#5d675f">Heb je je niet zelf aangemeld? Dan kun je dit bericht negeren.</p><p>Hartelijke groet,<br><strong>Matthijs van Dam</strong></p>`);
 return {subject,html};
}
module.exports={renderConfirmationMail,renderNewsletterExample,renderNativeConfirmationMail};
