from pathlib import Path
import re,html,json
P=Path(__file__).resolve().parents[1]
text=(P/'artikeltekst.md').read_text().split('\n---\n')[0]
parts=re.split(r'^## ([A-H]) — (.+)$',text,flags=re.M)[1:]
labels=['Een pijnlijke stap','De hiel','Enkel en kuit','Voetboog en grote teen','De grote teen','Het onderzoek','Loopanalyse','Het geheel']
alts=['Een voorbeeld van een gewone wandeling, zonder gesimuleerde aandoening.', 'De aanhechting van de peesplaat onder de hiel is gemarkeerd. De markering geeft een structuur aan, geen pijnmeting.', 'Het lichaam beweegt over de steunende voet. Gastrocnemius en soleus dragen via de achillespees kracht over.', 'Het schema links is afgeleid van de rechtervoet rechts. Bij een opgetilde teen loopt de peesplaat om het middenvoetskopje. In dit vereenvoudigde windlassmodel komt de boog omhoog; dit voorspelt geen spanning of pijn tijdens lopen.', 'Het gewricht aan de basis van de grote teen is gemarkeerd. De normale voorbeeldbeweging is geen simulatie van hallux rigidus.', 'Bij de gebogen knie gaat het onderbeen naar achteren. De gastrocnemius overspant knie en enkel; de soleus alleen de enkel. Deze schema’s zijn geen zelftest.', 'Camera’s, huidmarkers, een krachtplaat en elektroden geven verschillende informatie. Metingen worden samen met klachten en lichamelijk onderzoek beoordeeld.', 'Dezelfde wandelaar vervolgt zijn stap. Dit is geen voor-en-na-behandeling.']
ids=['een-gewone-stap','neerkomen','steun-nemen','voetboog','volgende-stap','kuit-en-klachten','loopanalyse','weer-naar-buiten']
def inline(s):
 s=html.escape(s)
 s=re.sub(r'\[([^]]+)\]\(([^)]+)\)',r'<a href="\2">\1</a>',s)
 s=re.sub(r'\*\*([^*]+)\*\*',r'<strong>\1</strong>',s)
 s=re.sub(r'\*([^*]+)\*',r'<em>\1</em>',s)
 def cite(m):
  expanded=re.sub(r'B(\d{2})[–-]B(\d{2})',lambda r: ', '.join(f'B{n:02}' for n in range(int(r[1]),int(r[2])+1)),m[0]);refs=re.findall(r'B\d{2}',expanded);return '<sup>'+', '.join(f'<a href="#bron-{r}" aria-label="Bron {r[1:]}">{r[1:]}</a>' for r in refs)+'</sup>'
 return re.sub(r'\[B\d{2}[^]]*\]',cite,s)
chapters=[]
for i in range(8):
 letter,title,body=parts[i*3:i*3+3]
 paras='\n'.join('<p>'+inline(p.replace('\n',' ').strip())+'</p>' for p in body.strip().split('\n\n') if p.strip())
 chapters.append(f'<section class="chapter" id="{ids[i]}" data-scene="{i}" aria-labelledby="h-{i}"><p class="eyebrow">{labels[i]}</p><h2 id="h-{i}">{html.escape(title)}</h2>{paras}<figure class="static-figure"><img src="stills/scene-{i}.svg" alt="{alts[i]}" width="720" height="620" loading="lazy"><figcaption>{alts[i]}</figcaption></figure></section>')
dossier=(P/'onderzoeksdossier.md').read_text()
refs=re.findall(r'\*\*(B\d+) — (.*?)\*\* \[([^]]+)\]\(([^)]+)\)',dossier)
sources=''.join(f'<li id="bron-{code}"><a href="{url}">{code[1:]}. {html.escape(title)}</a></li>' for code,title,_,url in refs)
head='''<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Als lopen pijn doet — lokaal concept</title><meta name="description" content="Een visueel verhaal over hielpijn, een stijve grote teen en de kuit: wat onderzoekt een orthopedisch chirurg? Lokaal concept."><link rel="stylesheet" href="story.css"></head><body><a class="skip" href="#verhaal">Naar het verhaal</a><header class="header"><a class="brand" href="../../index.html">Matthijs van Dam<span aria-hidden="true">.</span></a><nav aria-label="Hoofdnavigatie"><a href="../../artikelen.html">Artikelen</a><a href="#bronnen">Bronnen</a></nav></header>'''
page=head+'''<main><header class="hero"><p class="eyebrow">Wetenschap in beweging · 6 minuten</p><h1>Als lopen<br><em>pijn doet.</em></h1><p class="deck">Wat je grote teen, voetboog en kuit met een gewone stap te maken hebben.</p><div class="hero-bottom"><p>Door Matthijs van Dam · lokaal concept</p><button id="read-mode" hidden aria-pressed="false">Lees zonder animatie</button></div></header><article class="story-wrap" id="verhaal"><div class="stage" aria-hidden="true"><div class="stage-top"><span><i class="dot"></i>Een gewone wandeling</span><span id="view-label">Zijaanzicht</span></div><div class="drawing" id="drawing"></div><div class="legend" id="legend"></div><div class="stage-bottom"><div class="phase-track"><i id="phase-progress"></i></div><p><span id="phase-label">Eerste contact</span><span>Schematische illustratie</span></p></div></div><div class="flow">'''+''.join(chapters)+'''</div></article><section class="closing" id="bronnen"><p class="eyebrow">Achter het beeld</p><h2>Gebaseerd op onderzoek.<br>Getekend om te begrijpen.</h2><p>De hoofdbeweging gebruikt een bewerkte loopmeting van één deelnemer. De anatomie, voetboog en tenen zijn schematisch uitgewerkt. Het beeld is geen klinische reconstructie of persoonlijke loopanalyse.</p><p class="note">Bewegingsreferentie: Fukuchi, Fukuchi &amp; Duarte (2018), Walking Biomechanics Dataset, versie 6. CC BY 4.0. Bewerkt voor deze illustratie; verschillen tussen mensen blijven bestaan.</p><div class="links"><a href="https://doi.org/10.7717/peerj.4640">Lees het onderzoek ↗</a><a href="https://doi.org/10.6084/m9.figshare.5722711.v6">Bekijk de dataset ↗</a><a href="../../behandelingen.html">Voet- en enkelinformatie →</a></div><details id="source-details"><summary>Bronnen bij dit verhaal</summary><ol class="sources">'''+sources+'''</ol></details><p class="note">Lokaal concept. Medische en anatomische eindbeoordeling staan nog open.</p></section></main><footer><span>Matthijs van Dam</span><a href="../../disclaimer.html">Algemene informatie · medische grenzen</a></footer><script type="module" src="story.mjs"></script></body></html>'''
(P/'index.html').write_text(page)
rig=head.replace('href="#verhaal"','href="#rig-view"').replace('href="#bronnen"','href="index.html#bronnen"')+'''<main class="rig-tools"><p class="eyebrow">Lokale bewegingscontrole</p><h1>De stap, uitgekleed.</h1><p>Dezelfde rig als in het verhaal. Botlengten blijven constant. De bewerkte bronbeweging en contactmomenten zijn beschreven in het <a href="motion-manifest.json">manifest</a>.</p><label for="phase-input">Positie in de loopcyclus <output id="phase-output">0%</output></label><input id="phase-input" type="range" min="0" max="1000" value="0"><div class="rig-view" id="rig-view"></div><p><a href="index.html">Naar het scrollverhaal →</a></p><div class="rig-grid">'''+''.join(f'<figure><img src="stills/rig-{i}.svg" alt="Skeletcontrole op {v}% van de voorbeeldcyclus"><figcaption>{v}% van de voorbeeldcyclus</figcaption></figure>' for i,v in enumerate([0,8,18,30,45,52,61,75,90,100]))+'''</div></main><script type="module">import {illustration} from './renderer.mjs'; const data=await(await fetch('motion.json')).json();const input=document.querySelector('input');function render(){document.querySelector('#rig-view').innerHTML=illustration(data,input.value/1000,{debug:true});document.querySelector('output').textContent=Math.round(input.value/10)+'%';}input.addEventListener('input',render);render();</script></body></html>'''
(P/'rig.html').write_text(rig)
print('Built story, rig,',len(chapters),'chapters,',len(refs),'sources')
